CREATE DATABASE IF NOT EXISTS DDL;

CREATE TABLE empregado(
    PNOME VARCHAR(15) NOT NULL,
    MINICIAL CHAR,
    UNOME VARCHAR(15) NOT NULL,
    SSN BIGINT NOT NULL,
    DATANASC DATE,
    ENDERECO VARCHAR(80),
    SEXO BIT,
    SALARIO DECIMAL(10,2),
    SSN_SUPERVISOR BIGINT,
    DNUMERO_DEPARTAMENTO INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE departamento(
    DNOME VARCHAR(15) NOT NULL,
    SSN_EMPREGADO BIGINT,
    DATAINICIO DATE NOT NULL,
    DNUMERO INTEGER NOT NULL DEFAULT 1,
    
    PRIMARY KEY(DNUMERO),
    CONSTRAINT fk2
    FOREIGN KEY(SSN_EMPREGADO) REFERENCES EMPREGADO(SSN) ON DELETE SET NULL ON
    UPDATE CASCADE
);
CREATE TABLE projeto(
    PNOME VARCHAR(15) NOT NULL,
    DNUMERO_DEPARTAMENTO INTEGER DEFAULT 1,
    PLOCALIZACAO VARCHAR(50) NOT NULL,
    PNUMERO INTEGER NOT NULL DEFAULT 1,
    
    PRIMARY KEY(PNUMERO),
    CONSTRAINT fk3
    FOREIGN KEY(DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(DNUMERO) ON DELETE SET NULL ON
    UPDATE CASCADE
);

CREATE TABLE dependente(
    SSN_EMPREGADO BIGINT NOT NULL,
    NOME_DEPENDENTE VARCHAR(15) NOT NULL,
    SEXO BIT NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    PARENTESCO VARCHAR(15) NOT NULL,
    
    PRIMARY KEY(NOME_DEPENDENTE),
    PRIMARY KEY(SSN_EMPREGADO),
    CONSTRAINT fk4
    FOREIGN KEY(SSN_EMPREGADO) REFERENCES EMPREGADO(SSN) ON DELETE SET NULL ON
    UPDATE CASCADE
);

CREATE TABLE depto_localizadores(
    LNUMERO INTEGER NOT NULL DEFAULT 1,
    DLOCALIZACAO VARCHAR(50) NOT NULL,
    DNUMERO_DEPARTAMENTO INTEGER NOT NULL DEFAULT 1,
    
    PRIMARY KEY(LNUMERO),
    CONSTRAINT fk5
    FOREIGN KEY(DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(DNUMERO) ON DELETE SET NULL ON
    UPDATE CASCADE
);

CREATE TABLE trabalha_em(
    SSN_EMPREGADO BIGINT NOT NULL,
    PNUMERO_PROJETO INTEGER NOT NULL DEFAULT 1,
    HORAS TIME,
    
    PRIMARY KEY(SSN_EMPREGADO),
    PRIMARY KEY(PNUMERO_PROJETO),
    CONSTRAINT fk6
    FOREIGN KEY(SSN_EMPREGADO) REFERENCES EMPREGADO(SSN) ON DELETE SET NULL ON
    UPDATE CASCADE,
    CONSTRAINT fk7
    FOREIGN KEY(PNUMERO_PROJETO) REFERENCES PROJETO(PNUMERO) ON DELETE SET NULL ON
    UPDATE CASCADE
);