-- MySQL Script generated by MySQL Workbench
-- Wed Sep 14 15:42:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Faculdades
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Faculdades
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Faculdades` DEFAULT CHARACTER SET utf8 ;
USE `Faculdades` ;

-- -----------------------------------------------------
-- Table `Faculdades`.`Diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Faculdades`.`Diretor` (
  `idDiretor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `CPF` VARCHAR(45) NULL,
  PRIMARY KEY (`idDiretor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculdades`.`Faculdade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Faculdades`.`Faculdade` (
  `idFaculdade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `Diretor_idDiretor` INT NOT NULL,
  PRIMARY KEY (`idFaculdade`, `Diretor_idDiretor`),
  INDEX `fk_Faculdade_Diretor_idx` (`Diretor_idDiretor` ASC) VISIBLE,
  CONSTRAINT `fk_Faculdade_Diretor`
    FOREIGN KEY (`Diretor_idDiretor`)
    REFERENCES `Faculdades`.`Diretor` (`idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculdades`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Faculdades`.`Professor` (
  `idProfessor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `materia` VARCHAR(45) NOT NULL,
  `Faculdade_idFaculdade` INT NOT NULL,
  `Faculdade_Diretor_idDiretor` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Faculdade_idFaculdade`, `Faculdade_Diretor_idDiretor`),
  INDEX `fk_Professor_Faculdade1_idx` (`Faculdade_idFaculdade` ASC, `Faculdade_Diretor_idDiretor` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Faculdade1`
    FOREIGN KEY (`Faculdade_idFaculdade` , `Faculdade_Diretor_idDiretor`)
    REFERENCES `Faculdades`.`Faculdade` (`idFaculdade` , `Diretor_idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculdades`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Faculdades`.`Curso` (
  `idCurso` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculdades`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Faculdades`.`Aluno` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  `idade` INT NOT NULL,
  `periodo` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`matricula`, `Curso_idCurso`),
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Faculdades`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculdades`.`Professor_has_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Faculdades`.`Professor_has_Aluno` (
  `Professor_idProfessor` INT NOT NULL,
  `Professor_Faculdade_idFaculdade` INT NOT NULL,
  `Professor_Faculdade_Diretor_idDiretor` INT NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Professor_Faculdade_idFaculdade`, `Professor_Faculdade_Diretor_idDiretor`, `Aluno_matricula`),
  INDEX `fk_Professor_has_Aluno_Aluno1_idx` (`Aluno_matricula` ASC) VISIBLE,
  INDEX `fk_Professor_has_Aluno_Professor1_idx` (`Professor_idProfessor` ASC, `Professor_Faculdade_idFaculdade` ASC, `Professor_Faculdade_Diretor_idDiretor` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Aluno_Professor1`
    FOREIGN KEY (`Professor_idProfessor` , `Professor_Faculdade_idFaculdade` , `Professor_Faculdade_Diretor_idDiretor`)
    REFERENCES `Faculdades`.`Professor` (`idProfessor` , `Faculdade_idFaculdade` , `Faculdade_Diretor_idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `Faculdades`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
